name: dartmonitor
version: 1.0.0
description: >-
  Helps to Monitor and restart your Dart apps upon making changes.

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  args: ^1.5.0
  watcher: ^0.9.7+13
  colorize: any

executables:
  dartmoniitor: main